services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "directory_service"
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - database
  seq:
    container_name: ds-seq
    image: datalust/seq
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=admin
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - seq-data:/data
volumes:
  postgres_data:
  seq-data: